#!/usr/bin/python

import ConfigParser
import json
import os

def value(set_to):
    value = {}
    value["value"] = set_to
    return value

config = ConfigParser.ConfigParser()
config.read("cluster.ini")

params = {}
params["adminUsername"] = value(config.get('Cluster', 'username'))
params["adminPassword"] = value(config.get('Cluster', 'password'))
params["DNSNamePrefix"] = value(config.get('Cluster', 'dns_prefix'))
params["agentCount"] = value(int(config.get('Cluster', 'agent_count')))
params["masterCount"] = value(int(config.get('Cluster', 'master_count')))
params["sshRSAPublicKey"] = value(config.get('Cluster', 'ssh_public_key'))

# Create resource group

command = "azure group create " + config.get('Cluster', 'dns_prefix') + " " + config.get('Cluster', 'region')
os.system(command)

# Create Deployment

command = "azure group deployment create"
command = command + " " + config.get('Cluster', 'dns_prefix')
command = command + " " + config.get('Cluster', 'dns_prefix')
command = command + " --template-uri " + config.get('Template', 'template_url')
command = command + " -p '" + json.dumps(params) + "'"

os.system(command)


