#!/usr/bin/python

import acs_utils as acs
import logging
import optparse
         
def main():
    """Starts a new deployent."""

    p = optparse.OptionParser()
    p.add_option('--config_file', '-c', default="cluster.ini",
                 help="Define the configuration file to use.")
    options, arguments = p.parse_args()
 
    config = acs.getConfig(options.config_file)
    logging.debug("config file: " + options.config_file)
    acs.createDeployment(config)

if __name__ == '__main__':
    main()
