#!/usr/bin/python

import acs_utils as acs

def log(msg):
    print msg
    print

config = acs.getConfig('mesos_cluster.ini')

log("Check current apps")
acs.marathonCommand(config, 'apps')
log("End test")

