#!/usr/bin/python

from acs_utils import *
import requests
import sys
import time

acs = ACSUtils('mesos_cluster.ini')
log = ACSLog()

response = acs.openMesosTunnel()
log.info(response);

log.info("Start: Check current apps")
log.debug(acs.marathonCommand('apps'))
log.info("End")

log.info("Deploy a two container app")
with open ('marathon-app.json', "r") as marathonfile:
    data=marathonfile.read().replace('\n', '').replace("\"", "\\\"")

log.debug(acs.marathonCommand('groups', 'POST', data))
log.debug("End")

log.debug("Check the application is running")
for i in range (0,10):
    log.debug("Attempt to access service " + str(i) + " of 10")
    try:
        r = requests.get("http://" + acs.getAgentsFQDN(config))
        if r.status_code == 200:
            log.debug("Got a 200 response from the application")
            break
    except:
        log.debug("Attempt failed, sleeping for 5 seconds")
        time.sleep (5)

if i >= 9: 
    log.error("TESTING: Application never responded")
log.info("End")

log.info("Remove the app")
acs.marathonCommand('groups/azure', 'DELETE')
log.info("End")


