#!/usr/bin/python

from acs_utils import *

acs = ACSUtils("swarm_cluster.ini")
log = ACSLog()

response = acs.openSwarmTunnel(      )
log.info(response);

log.info("docker info")
response = acs.dockerCommand('info')
log.info(response);
log.info("End test")

log.info("docker ps")
response = acs.dockerCommand('ps')
log.info(response);
log.info("End test")

log.info("Deploy a two container app")
response = acs.composeCommand('up', options = '-d')
log.info(response);
log.info("End")

log.info("docker ps")
response = acs.dockerCommand('ps')
log.info(response);
log.info("End test")

log.info("Stop the applicaton")
response = acs.composeCommand('stop')
log.info(response);
log.info("End test")


log.info("docker ps")
response = acs.dockerCommand('ps')
log.info(response);
log.info("End test")
