#!/usr/bin/python

from acs_utils import ACSUtils
import logging
import optparse
         
def main():
    """Starts a new deployent."""

    p = optparse.OptionParser()
    p.add_option('--config_file', '-c', default="cluster.ini",
                 help="define the configuration file to use. Default is 'cluster.ini'")
    options, arguments = p.parse_args()
 
    acs = ACSUtils(options.config_file)
    acs.createDeployment()

if __name__ == '__main__':
    main()
